image: maven:3-jdk-13

stages:
  - build
  - test
  - deploy

build_a:
  stage: build
  script:
    - echo "build"

test:
  stage: test
  script:
    - echo "test"

deploy:
  stage: deploy
  script:
    - echo "deploy"
