image: maven:3-jdk-17

stages:
  - clean
  - build
  - test

clean:
  stage: clean
  script:
    - mvn clean

build:
  stage: build
  script:
    - mvn -B package

test:
  stage: test
  script:
    - mvn test
